name: Unit Tests
on: push
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: zh5uo8/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cd tests && cmake . && make
      - name: Teszt futtatas
        run: make unittest